apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels: { app: nodejs-app }
spec:
  replicas: 2
  selector:
    matchLabels: { app: nodejs-app }
  template:
    metadata:
      labels: { app: nodejs-app }
    spec:
      containers:
        - name: node-app
          image: __IMAGE_PLACEHOLDER__
          ports: [{ containerPort: 3000 }]
---
apiVersion: v1
kind: Service
metadata: { name: nodejs-service }
spec:
  selector: { app: nodejs-app }
  ports: [{ protocol: TCP, port: 80, targetPort: 3000 }]
  type: ClusterIP
